#!/bin/bash

#
# Compares Apache Cayenne release checksums and signature using OSX tools
# 
# Checksum file format is expected to be the one prodiced by "gpg":
#
#   gpg --print-md MD5 file
#   gpg --print-md SHA512 file
#

EXIT_CODE=0
FILES="ls *.gz *.dmg *.zip"
for FILE in `$FILES` ; do

	echo ""
	echo "$FILE: verifying checksums and signatures..."

	SHA512_ACTUAL=`shasum -a 512 $FILE |perl -n -e 's/^([[:xdigit:]]+)\s.+$/\1/; print "$_\n"' | tr [a-z] [A-Z]`
	SHA512_EXPECTED=`cat $FILE.sha512 |tr '\n' ' '|perl -n -e 's/\s//g; s/^.+:([[:xdigit:]]+)$/\1/; print "$_\n"'`

	echo "SHA512 Actual  : $SHA512_ACTUAL"
	echo -n "SHA512 Expected: $SHA512_EXPECTED"
	if [ "$SHA512_ACTUAL" == "$SHA512_EXPECTED" ]; then
		echo "... matches"
	else 
		echo "   *** does not match"
		EXIT_CODE=1
	fi

	echo "Checking signature...."
	gpg -q --verify "$FILE.asc" "$FILE"
	if [ "$?" == "0" ] ; then 
		echo "... valid"
	else 
		echo "*** INVALID"
		EXIT_CODE=1
	fi
done

echo ""
if [ "$EXIT_CODE" == "0" ] ; then 
	echo "All checks have passed successfully."
	echo "Files verified: `$FILES |tr '\n' ' '`"
else 
	echo "*** Some checks have failed. Read the output of this command above for details."
	EXIT_CODE=1
fi

exit $EXIT_CODE